default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  irb120_joint_1:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 5.0
  irb120_joint_2:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 5.0
  irb120_joint_3:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 5.0
  irb120_joint_4:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 5.0
  irb120_joint_5:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: true
    max_acceleration: 5.0
  irb120_joint_6:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: true
    max_acceleration: 0.5
  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: true
    max_acceleration: 0.5
