# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    ur10e_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
ur10e_arm_controller:
  ros__parameters:
    joints:
      - ur10e_shoulder_pan_joint
      - ur10e_shoulder_lift_joint
      - ur10e_elbow_joint
      - ur10e_wrist_1_joint
      - ur10e_wrist_2_joint
      - ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: left_finger_joint
    use_effort_interface: true
    use_speed_interface: true
    max_effort: 5.0
    goal_tolerance: 0.001
